@startuml
allow_mixing
rectangle APIs as apis{
    top to bottom direction
    agent "POST: /api/v1/file" as apis.post
    note bottom of apis.post
        create a file submission
    end note
    agent "PUT: /api/v1/file/{id}" as apis.put
    note bottom of apis.put
        update file based on
        the file submission
    end note
    agent "GET: /api/v1/file" as apis.get
    note bottom of apis.get
        retrieve the file submission
    end note
    agent "Delete: /api/v1/file/{id}" as apis.delete
    note bottom of apis.delete
        delete file
    end note
}

rectangle Entity{
    class FileSubmission {
        UUID id
        String description
        Long size
        String hash
        byte[] bytes
        Date lastModified
    }

    object FileSubmissionExample {
        id = "79caedff-2905-4df1-affd-fbd35c867f05"
        description = "testing file"
        size = 1000L
        hash = "dec40b74bfc6ffa07d6d3e8efd8f1dc7788e778266f5e65602d800499ba30849"
        bytes = byte[]
        lastModified = 1647099049114
    }

    FileSubmission -[dashed]-> FileSubmissionExample : Example


}

rectangle Post as postRect{
    class PostRequest{}
    class PostResponse{
        id: String
        size: Long
        hash: String
    }
}

rectangle Put as putRect{
    class PutRequest{
        file: MultipartFile
    }
    class PutResponse {
        id: String
        size: Long
        hash: String
    }
}

PostResponse -[dashed]- FileSubmission : partial data
PutResponse -[dashed]- FileSubmission : partial data

rectangle Get as getRect{
    rectangle GetResponsePNG[
        GetResponse (PNG)
        ---
        content-type: img/png
    ]
    rectangle GetResponseGIF[
        GetResponse (GIF)
        ---
        content-type: img/gif
    ]
    rectangle GetResponseJPEG[
        GetResponse (JPEG)
        ---
        content-type: img/jpeg
    ]
    rectangle GetResponseOctet[
        GetResponse (Octet)
        ---
        content-type: application/octet-stream
    ]
}

rectangle Delete as deleteRect{
    class DeleteResponse {
        id: String
        size: Long
        hash: String
    }
}

DeleteResponse -[dashed]- FileSubmission : partial data

apis.post -[dashed]-> postRect
apis.put -[dashed]-> putRect
apis.get -[dashed]-> getRect
apis.delete -[dashed]-> deleteRect

@enduml