@startuml

rectangle "SFS (Simple file storage)" as rect #green {
    (create file) as cf
    (delete file) as df
    (update file) as uf
    (get file) as gf
}

:Admin User: as admin
:User: as user
agent "Update Agent" as appClient

cf -- admin
df -- admin
uf -- appClient
gf -- user
@enduml
